name: CI

on:
  push:
  pull_request:

jobs:
  lint-type:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install tools
        run: |
          python -m pip install -U pip
          python -m pip install -U ruff black mypy
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Mypy
        run: mypy .
